version: '3'
services:
  eurekaserver:
    image: eurekaserver
    ports:
      - 8711:8711
  cbs-microservice:
    image: cbs-microservice
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://eurekaserver:8711/eureka
    depends_on:
      - eurekaserver
    ports:
      - 8200:8200
  originatorservice:
    image: originatorservice
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://eurekaserver:8711/eureka
    depends_on:
      - eurekaserver
    ports:
      - 8100:8100
  zuulserver:
    image: zuulserver
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://eurekaserver:8711/eureka
    depends_on:
      - eurekaserver
    ports:
      - 8300:8300
